POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{"username":"sam","email":"s@gmail.com", "password":"11"}

###

POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{"username":"sam","email":"s@gmail.com", "password":"11"}

###

POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token 6b5d56bbfe687812248c16026cf8121538fe82a4

{}

###

GET http://127.0.0.1:8000/api/hello/
Content-Type: application/json
Authorization: Token 2f4d22c829e14b3363ba54736bb01012c5728971


###

POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token 97c6980c050572c5ab3d78502a32cf5fbecc4900
